services:

  web01:
    build:
      context: ./page
      dockerfile: Dockerfile.c01
    image: c01
    container_name: c01
    networks:
      - asa-net  

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile.bind
    image: bind9
    container_name: bind9
    ports:
      - "53:53/udp"
      - "953/tcp"
    networks:
      - asa-net

  proxy:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.proxy
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - web01
    networks:
      - asa-net

networks:
  asa-net:
    driver: bridge
